version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Terraform
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "terraform"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Examples
  - package-ecosystem: "terraform"
    directory: "/examples/minimal"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "terraform"

  - package-ecosystem: "terraform"
    directory: "/examples/with-scheduler"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "terraform"

  - package-ecosystem: "terraform"
    directory: "/examples/site-to-site"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "terraform"

  # Python dependencies (for Cloud Functions)
  - package-ecosystem: "pip"
    directory: "/modules/scheduler/functions/start-instance"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "pip"
    directory: "/modules/scheduler/functions/stop-instance"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
