blank_issues_enabled: false
contact_links:
  - name: Security Issues
    url: https://github.com/dieguezz/terraform-gcp-vpn/blob/main/SECURITY.md
    about: Please follow the security policy for reporting vulnerabilities.
